--- 
build_script: 
  - 
    cmd: "build.cmd Release"
environment:
  nuget_key:
    secure: kJDsbnsi5l4w3fpFkTdIueBLc/NhzjYSYaNQ8hflQaGhyjK8H5a+r6l3t8BjPhCB
image: "Visual Studio 2017"
skip_tags: true
version: "1.3.0.{build}"
test:
  assemblies:
    only:
    - ./tests/**/bin/Release/net462/FsRandom.Tests.dll